# Generated by Django 4.1.1 on 2022-09-30 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodSupply',
            fields=[
                ('supply_id', models.AutoField(primary_key=True, serialize=False)),
                ('aplus_amount', models.IntegerField(default=0)),
                ('amin_amount', models.IntegerField(default=0)),
                ('bplus_amount', models.IntegerField(default=0)),
                ('bmin_amount', models.IntegerField(default=0)),
                ('abplus_amount', models.IntegerField(default=0)),
                ('abmin_amount', models.IntegerField(default=0)),
                ('oplus_amount', models.IntegerField(default=0)),
                ('omin_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('I', 'Individual'), ('O', 'Organization')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.user')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('contact_number', models.CharField(max_length=11)),
                ('health_condition', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-'), ('O-', 'O-')], max_length=3)),
                ('individual_type', models.CharField(choices=[('D', 'Donor'), ('R', 'Recipient')], max_length=1)),
            ],
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.user')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('contact_number', models.CharField(max_length=11)),
                ('org_type', models.CharField(choices=[('H', 'Hospital'), ('B', 'Blood Bank')], max_length=1)),
                ('blood_supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.bloodsupply')),
            ],
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.organization')),
            ],
            bases=('accounts.organization',),
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('individual_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.individual')),
            ],
            bases=('accounts.individual',),
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.organization')),
            ],
            bases=('accounts.organization',),
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('individual_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.individual')),
            ],
            bases=('accounts.individual',),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField()),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-'), ('O-', 'O-')], max_length=3)),
                ('quantity', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.bloodbank')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Transfusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfusion_date', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hospital')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.recipient')),
            ],
            options={
                'unique_together': {('recipient', 'transfusion_date')},
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.bloodbank')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.donor')),
            ],
            options={
                'unique_together': {('donor', 'donation_date')},
            },
        ),
    ]
