# Generated by Django 4.1.1 on 2022-10-12 09:01

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='default.png', upload_to=accounts.models.image_path, verbose_name='Profile picture'),
        ),
    ]
