# Generated by Django 4.1.1 on 2022-10-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfusion',
            name='requested_blood_type',
            field=models.CharField(default='A+', max_length=3),
            preserve_default=False,
        ),
    ]
