# Generated by Django 4.1.1 on 2022-09-30 05:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_organization_blood_supply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='contact_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(regex='^(09|\\+639)\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contact_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(regex='^(09|\\+639)\\d{9}$')]),
        ),
    ]
