# Generated by Django 4.1.1 on 2022-10-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_individual_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='health_condition',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Health conditions (optional)'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='weight',
            field=models.FloatField(verbose_name='Weight (kg)'),
        ),
    ]
